#!/bin/bash
PKGNAME="kmod"
CONFIGUREOPT="--silent --with-xz --with-zlib --disable-manpages --sysconfdir=/etc --with-rootlibdir=/lib --bindir=/bin --prefix=/usr"

#include global config script
BUILDCONFIGPATH="../../build.config"
BUILDCONFIGABSPATH="$(readlink -e $BUILDCONFIGPATH)"
source "$BUILDCONFIGABSPATH"

#define needed dirs
SOURCEPATH="../../$SOURCEDIRNAME/$PKGNAME"
BUILDPATH="../../$BUILDDIRNAME/$PKGNAME"
DESTPATH="../../$ROOTFSDIRNAME/$PKGNAME"
PKGPATH="../../$PKGDIRNAME"

#convert relative path to absolute
SOURCEABSPATH="$(readlink -e $SOURCEPATH)"
BUILDABSPATH="$(readlink -e $BUILDPATH)"
BUILDCONFIGABSPATH="$(readlink -e $BUILDCONFIGPATH)"
DESTABSPATH="$(readlink -e $DESTPATH)"
PKGABSPATH="$(readlink -e $PKGPATH)"
PWD=`pwd`

if [ -d "$SOURCEABSPATH" ]; then
        if [ -d "$DESTABSPATH" ]; then
                rm -rf "$DESTABSPATH"
        fi
        mkdir "$DESTPATH"
	DESTABSPATH="$(readlink -e $DESTPATH)"

	if [ -d "$BUILDABSPATH" ]; then
		rm -rf "$BUILDABSPATH"
	fi
	mkdir "$BUILDPATH"

	#start building
        cd "$BUILDPATH"
	echo "=== Configuring $PKGNAME with CFlags=$BUILDCFLAGS ==="
	eval "make clear | tee buildlog-clear"
	eval "CFLAGS=\"$BUILDCFLAGS\" $SOURCEPATH/configure $CONFIGUREOPT > buildlog-configure"
        
	echo "=== Compiling $PKGNAME with CFlags=$BUILDCFLAGS ==="
	eval "make -s V=0 | tee buildlog-clear"

        echo "=== Installing $PKGNAME to package directory and rootfs ==="
	eval "make -s V=0 install DESTDIR=$DESTABSPATH | tee buildlog-install"

	if [ -d "$DESTABSPATH" ]; then
		#remove garbage
		eval "rm -rf $DESTABSPATH/usr/share"
		eval "rm -rf $DESTABSPATH/usr/lib/pkgconfig"
		eval "strip -s $DESTABSPATH/bin/*"
		eval "strip -s $DESTABSPATH/usr/lib/*"
                eval "strip -s $DESTABSPATH/lib/*"
		eval "mkdir -p $DESTABSPATH/sbin"
		eval "cd $DESTABSPATH/sbin"
		eval "ln -sv ../bin/kmod ./depmod"
                eval "ln -sv ../bin/kmod ./insmod"
                eval "ln -sv ../bin/kmod ./lsmod"
                eval "ln -sv ../bin/kmod ./modinfo"
                eval "ln -sv ../bin/kmod ./modprobe"
                eval "ln -sv ../bin/kmod ./rmmod"
		eval "cd $DESTABSPATH/bin"
		eval "ln -sv ./kmod ./lsmod"

		#create package
		PKGFILEPATH="$PKGABSPATH/$PKGNAME.$PKG_EXT"
		echo "=== creating $PKGFILEPATH ==="
		eval "$PKG_CMD $PKGFILEPATH $DESTABSPATH/*"
	fi
else
	echo "!! $SOURCEABSPATH does not exists (from $PWD)"
fi
