#!/bin/bash
PKGNAME="bash"
CONFIGUREOPT="--enable-static-link --without-bash-malloc --bindir=/bin --prefix=/usr"

#include global config script
BUILDCONFIGPATH="../../build.config"
BUILDCONFIGABSPATH="$(readlink -e $BUILDCONFIGPATH)"
source "$BUILDCONFIGABSPATH"

#define needed dirs
SOURCEPATH="../../$SOURCEDIRNAME/$PKGNAME"
BUILDPATH="../../$BUILDDIRNAME/$PKGNAME"
DESTPATH="../../$ROOTFSDIRNAME/$PKGNAME"
PKGPATH="../../$PKGDIRNAME"

#convert relative path to absolute
SOURCEABSPATH="$(readlink -e $SOURCEPATH)"
BUILDABSPATH="$(readlink -e $BUILDPATH)"
BUILDCONFIGABSPATH="$(readlink -e $BUILDCONFIGPATH)"
DESTABSPATH="$(readlink -e $DESTPATH)"
PKGABSPATH="$(readlink -e $PKGPATH)"
PWD=`pwd`

if [ -d "$SOURCEABSPATH" ]; then
        if [ -d "$DESTABSPATH" ]; then
                rm -rf "$DESTABSPATH"
        fi
        mkdir "$DESTPATH"
	DESTABSPATH="$(readlink -e $DESTPATH)"

	if [ -d "$BUILDABSPATH" ]; then
		rm -rf "$BUILDABSPATH"
	fi
	mkdir "$BUILDPATH"

	#start building
	cd "$SOURCEPATH"
	eval "wget http://www.linuxfromscratch.org/patches/lfs/development/bash-4.3.30-upstream_fixes-2.patch"
	eval "patch -Np1 -i ./bash-4.3.30-upstream_fixes-2.patch"

        cd "$BUILDPATH"
	echo "=== Compiling $PKGNAME with CFlags=$BUILDCFLAGS ==="
	eval "make clear"
	eval "CFLAGS=\"$BUILDCFLAGS\" $SOURCEPATH/configure $CONFIGUREOPT"
	eval "make"
	eval "make install DESTDIR=$DESTABSPATH"

	if [ -d "$DESTABSPATH" ]; then
		#remove garbage
		eval "rm -rf $DESTABSPATH/usr/share"
		eval "rm $DESTABSPATH/bin/bashbug"
		eval "strip -s $DESTABSPATH/bin/*"

		#create package
		PKGFILEPATH="$PKGABSPATH/$PKGNAME.$PKG_EXT"
		echo "=== creating $PKGFILEPATH ==="
		eval "$PKG_CMD $PKGFILEPATH $DESTABSPATH/*"
	fi
else
	echo "!! $SOURCEABSPATH does not exists (from $PWD)"
fi
