#!/bin/bash
PKGNAME="sysvinit"

#include global config script
BUILDCONFIGPATH="../../build.config"
BUILDCONFIGABSPATH="$(readlink -e $BUILDCONFIGPATH)"
source "$BUILDCONFIGABSPATH"

#define needed dirs
SOURCEPATH="../../$SOURCEDIRNAME/$PKGNAME"
BUILDPATH="../../$BUILDDIRNAME/$PKGNAME"
DESTPATH="../../$ROOTFSDIRNAME/$PKGNAME"
PKGPATH="../../$PKGDIRNAME"

#convert relative path to absolute
SOURCEABSPATH="$(readlink -e $SOURCEPATH)"
BUILDABSPATH="$(readlink -e $BUILDPATH)"
BUILDCONFIGABSPATH="$(readlink -e $BUILDCONFIGPATH)"
DESTABSPATH="$(readlink -e $DESTPATH)"
PKGABSPATH="$(readlink -e $PKGPATH)"
PWD=`pwd`

if [ -d "$SOURCEABSPATH" ]; then
        if [ -d "$DESTABSPATH" ]; then
                rm -rf "$DESTABSPATH"
        fi
        mkdir "$DESTPATH"
	DESTABSPATH="$(readlink -e $DESTPATH)"

	if [ -d "$BUILDABSPATH" ]; then
		rm -rf "$BUILDABSPATH"
	fi
	mkdir "$BUILDPATH"

	#start building
	cd "$SOURCEPATH"
	eval "wget -q -N http://www.linuxfromscratch.org/patches/lfs/development/sysvinit-2.88dsf-consolidated-1.patch -O sysvinit1.patch"
	eval "patch -Np1 -i ./sysvinit1.patch | tee buildlog-patch"

	echo "=== Compiling $PKGNAME with CFlags=$BUILDCFLAGS ==="
	eval "make -s CFLAGS=\"$BUILDCFLAGS\" V=0 -C src | tee buildlog-clear"

        echo "=== Installing $PKGNAME to package directory and rootfs ==="
	eval "mkdir -p $DESTABSPATH/sbin"
	eval "cp ./src/bootlogd $DESTABSPATH/sbin/"
        eval "cp ./src/fstab-decode $DESTABSPATH/sbin/"
        eval "cp ./src/halt $DESTABSPATH/sbin/"
        eval "cp ./src/init $DESTABSPATH/sbin/"
        eval "cp ./src/killall5 $DESTABSPATH/sbin/"
        eval "cp ./src/runlevel $DESTABSPATH/sbin/"
        eval "cp ./src/shutdown $DESTABSPATH/sbin/"       

	if [ -d "$DESTABSPATH" ]; then
		#remove garbage
		eval "strip -s $DESTABSPATH/sbin/*"

		#create package
		PKGFILEPATH="$PKGABSPATH/$PKGNAME.$PKG_EXT"
		echo "=== creating $PKGFILEPATH ==="
		eval "$PKG_CMD $PKGFILEPATH $DESTABSPATH/*"
	fi
else
	echo "!! $SOURCEABSPATH does not exists (from $PWD)"
fi
